export const Actions = {
  HYDRATE: 'HYDRATE',

  ADD_ITEM: 'ADD_ITEM',
  UPDATE_ITEM: 'UPDATE_ITEM',
  DELETE_ITEM: 'DELETE_ITEM',
  SET_QUANTITY: 'SET_QUANTITY',
  ADJUST_QUANTITY: 'ADJUST_QUANTITY',

  ADD_TO_CAULDRON: 'ADD_TO_CAULDRON',
  UPDATE_CAULDRON_AMOUNT: 'UPDATE_CAULDRON_AMOUNT',
  REMOVE_FROM_CAULDRON: 'REMOVE_FROM_CAULDRON',
  CLEAR_CAULDRON: 'CLEAR_CAULDRON',
  BREW_CAULDRON: 'BREW_CAULDRON',
  RESTOCK_FROM_CAULDRON: 'RESTOCK_FROM_CAULDRON',

  SAVE_RECIPE: 'SAVE_RECIPE',
  UPDATE_RECIPE: 'UPDATE_RECIPE',
  DELETE_RECIPE: 'DELETE_RECIPE',
  BREW_RECIPE: 'BREW_RECIPE',
};
